version: '3.4'

services:

   transcope_svc:
     image: api_transcope
     container_name: cont_transcope
     build:
      context: .
      dockerfile: Dockerfile.API_TranScope
     ports:
        - "5000:80"
     environment:
       - R_DBSection__CommandTimeout=600
       - R_DBSection__R_DBConfigs__0__Name=R_DefaultConnectionString
       - R_DBSection__R_DBConfigs__0__ConnectionString=server=192.168.2.7,1433;Initial Catalog=Realta_DB;User ID=sa;Password=F8093F6CAEAFDDC975507D0EEBD760E4;
       - R_DBSection__R_DBConfigs__0__ProviderName=System.Data.SqlClient
       - R_DBSection__R_DBConfigs__0__KeywordForPassword=Password
       - R_DBSection__R_DBConfigs__1__Name=R_ReportConnectionString
       - R_DBSection__R_DBConfigs__1__ConnectionString=server=172.16.5.57,57746;Initial Catalog=Realta_DB;User ID=sa;Password=F8093F6CAEAFDDC975507D0EEBD760E4;
       - R_DBSection__R_DBConfigs__1__ProviderName=System.Data.SqlClient
       - R_DBSection__R_DBConfigs__1__KeywordForPassword=Password